import pandas as pd

states = [
    ('ME', 'Northeast', 'State'),
    ('NH', 'Northeast', 'State'),
    ('VT', 'Northeast', 'State'),
    ('MA', 'Northeast', 'State'),
    ('RI', 'Northeast', 'State'),
    ('CT', 'Northeast', 'State'),
    ('NY', 'Northeast', 'State'),
    ('NJ', 'Northeast', 'State'),
    ('PA', 'Northeast', 'State'),
    ('MD', 'South', 'State'),
    ('DE', 'South', 'State'),
    ('DC', 'South', 'State'),
    ('VA', 'South', 'State'),
    ('WV', 'South', 'State'),
    ('KY', 'South', 'State'),
    ('TN', 'South', 'State'),
    ('NC', 'South', 'State'),
    ('SC', 'South', 'State'),
    ('GA', 'South', 'State'),
    ('AL', 'South', 'State'),
    ('MS', 'South', 'State'),
    ('FL', 'South', 'State'),
    ('TX', 'South', 'State'),
    ('LA', 'South', 'State'),
    ('OH', 'Midwest', 'State'),
    ('MI', 'Midwest', 'State'),
    ('IN', 'Midwest', 'State'),
    ('IL', 'Midwest', 'State'),
    ('WI', 'Midwest', 'State'),
    ('MN', 'Midwest', 'State'),
    ('IA', 'Midwest', 'State'),
    ('MO', 'Midwest', 'State'),
    ('ND', 'Midwest', 'State'),
    ('SD', 'Midwest', 'State'),
    ('NE', 'Midwest', 'State'),
    ('KS', 'Midwest', 'State'),
    ('WA', 'Pacific Northwest', 'State'),
    ('OR', 'Pacific Northwest', 'State'),
    ('ID', 'Pacific Northwest', 'State'),
    ('MT', 'Pacific Northwest', 'State'),
    ('WY', 'Pacific Northwest', 'State'),
    ('AK', 'Pacific Northwest', 'State'),
    ('CA', 'Southwest', 'State'),
    ('NV', 'Southwest', 'State'),
    ('UT', 'Southwest', 'State'),
    ('AZ', 'Southwest', 'State'),
    ('NM', 'Southwest', 'State'),
    ('CO', 'Southwest', 'State'),
    ('HI', 'Hawaii and Pacific Islands', 'State'),
    ('GU', 'Hawaii and Pacific Islands', 'State'),
    ('VI', 'Hawaii and Pacific Islands', 'State'),
    ('PR', 'Hawaii and Pacific Islands', 'State'),
    ('MP', 'Hawaii and Pacific Islands', 'State'),
    ('FM', 'National', 'State'),
    ('MH', 'Hawaii and Pacific Islands', 'State'),
    ('PW', 'Hawaii and Pacific Islands', 'State'),
    ('AS', 'Hawaii and Pacific Islands', 'State'),
    ('PW', 'Hawaii and Pacific Islands', 'State'),
    ('AE', 'National', 'State'),
    ('AA', 'National', 'State'),
    ('AE', 'National', 'State'),
    ('AP', 'National', 'State'),
    ('OK', 'Central', 'State'),
    ('AR', 'Central', 'State')
]

platform = [
    ('M', 'Mobile', 'Platform'),
    ('D', 'Desktop', 'Platform')
]

card = [
    (1, 'American Express', 'Card'),
    (2, 'Diners Club / Carte Blanche', 'Card'),
    (3, 'Discover', 'Card'),
    (4, 'JCB', 'Card'),
    (5, 'Maestro', 'Card'),
    (6, 'Mastercard', 'Card'),
    (7, 'VISA', 'Card'),
    (8, 'Voyager', 'Card')
]

job_list = [
    ('Solicitor', 'LL', 'Job'),
    ('Advertising art director', 'DA', 'Job'),
    ('Purchasing manager', 'FA', 'Job'),
    ('Medical secretary', 'HMH', 'Job'),
    ('Designer, multimedia', 'DA', 'Job'),
    ('Mining engineer', 'TE', 'Job'),
    ('Dietitian', 'HM', 'Job'),
    ('Fish farm manager', 'FT', 'Job'),
    ('Soil scientist', 'SR', 'Job'),
    ('Copywriter, advertising', 'DA', 'Job'),
    ('Accountant, chartered public finance', 'FA', 'Job'),
    ('Corporate treasurer', 'FA', 'Job'),
    ('Scientist, water quality', 'SR', 'Job'),
    ('Field seismologist', 'TE', 'Job'),
    ('Acupuncturist', 'HM', 'Job'),
    ('Building control surveyor', 'TE', 'Job'),
    ('Television camera operator', 'FT', 'Job'),
    ('Warden/ranger', 'FT', 'Job'),
    ('Commissioning editor', 'FT', 'Job'),
    ('Designer, jewellery', 'DA', 'Job'),
    ('Oceanographer', 'SR', 'Job'),
    ('Company secretary', 'LL', 'Job'),
    ('Ergonomist', 'TE', 'Job'),
    ('Furniture designer', 'DA', 'Job'),
    ('Development worker, community', 'ED', 'Job'),
    ('Conservator, furniture', 'DA', 'Job'),
    ('Engineer, petroleum', 'TE', 'Job'),
    ('Control and instrumentation engineer', 'TE', 'Job'),
    ('Designer, television/film set', 'FT', 'Job'),
    ('Call centre manager', 'FT', 'Job'),
    ('Food technologist', 'HM', 'Job'),
    ('Environmental consultant', 'SR', 'Job'),
    ('Set designer', 'FT', 'Job'),
    ('Fisheries officer', 'FT', 'Job'),
    ('Medical physicist', 'HMH', 'Job'),
    ('Wellsite geologist', 'TE', 'Job'),
    ('Engineer, manufacturing', 'TE', 'Job'),
    ('Legal executive', 'LL', 'Job'),
    ('IT consultant', 'TE', 'Job'),
    ('Art therapist', 'HMH', 'Job'),
    ('Charity fundraiser', 'FA', 'Job'),
    ('Research scientist (medical)', 'HMH', 'Job'),
    ('Proofreader', 'DA', 'Job'),
    ('Librarian, public', 'ED', 'Job'),
    ('Therapist, horticultural', 'HMH', 'Job'),
    ('Cabin crew', 'FT', 'Job'),
    ('Farm manager', 'AG', 'Job'),
    ('Hydrogeologist', 'TE', 'Job'),
    ('Interpreter', 'TE', 'Job'),
    ('Lexicographer', 'ED', 'Job'),
    ('Lawyer', 'LL', 'Job'),
    ('Engineer, electronics', 'TE', 'Job'),
    ('Medical sales representative', 'HM', 'Job'),
    ('Occupational hygienist', 'HMH', 'Job'),
    ('Advertising account executive', 'DA', 'Job'),
    ('Multimedia specialist', 'DA', 'Job'),
    ('Outdoor activities/education manager', 'ED', 'Job'),
    ('Health physicist', 'HMH', 'Job'),
    ('Risk analyst', 'FA', 'Job'),
    ('Adult guidance worker', 'HMH', 'Job'),
    ('Television floor manager', 'FT', 'Job'),
    ('Teacher, English as a foreign language', 'ED', 'Job'),
    ('Sport and exercise psychologist', 'HMH', 'Job'),
    ('Communications engineer', 'TE', 'Job'),
    ('Chemical engineer', 'TE', 'Job'),
    ('Phytotherapist', 'HMH', 'Job'),
    ('Financial adviser', 'FA', 'Job'),
    ('Psychiatric nurse', 'HMH', 'Job'),
    ('Hospital doctor', 'HMH', 'Job'),
    ('Insurance claims handler', 'FA', 'Job'),
    ('Hydrologist', 'SR', 'Job'),
    ('Engineer, maintenance (IT)', 'TE', 'Job'),
    ('Agricultural engineer', 'AG', 'Job'),
    ('Optometrist', 'HM', 'Job'),
    ('Engineer, communications', 'TE', 'Job'),
    ('Biomedical engineer', 'HMH', 'Job'),
    ('Production manager', 'FT', 'Job'),
    ('Cartographer', 'SR', 'Job'),
    ('Operational investment banker', 'FA', 'Job'),
    ('Scientist, biomedical', 'SR', 'Job'),
    ('Field trials officer', 'AG', 'Job'),
    ('Seismic interpreter', 'TE', 'Job'),
    ('Risk manager', 'FA', 'Job'),
    ('Mudlogger', 'AG', 'Job'),
    ('Podiatrist', 'HM', 'Job'),
    ('Administrator, arts', 'DA', 'Job'),
    ('Production assistant, radio', 'FT', 'Job'),
    ('Customer service manager', 'FA', 'Job'),
    ('Sales executive', 'FA', 'Job'),
    ('Learning disability nurse', 'HMH', 'Job'),
    ('Printmaker', 'DA', 'Job'),
    ('Journalist, newspaper', 'FT', 'Job'),
    ('Television production assistant', 'FT', 'Job'),
    ('Location manager', 'FT', 'Job'),
    ('Financial manager', 'FA', 'Job'),
    ('Primary school teacher', 'ED', 'Job'),
    ('Fitness centre manager', 'HMH', 'Job'),
    ('Merchandiser, retail', 'FA', 'Job'),
    ('Health and safety adviser', 'HMH', 'Job'),
	('Office manager', 'FA', 'Job'),
    ('Engineer, materials', 'TE', 'Job'),
    ('Site engineer', 'TE', 'Job'),
    ('Broadcast journalist', 'FT', 'Job'),
    ('Teacher, special educational needs', 'ED', 'Job'),
    ('Insurance risk surveyor', 'FA', 'Job'),
    ('Ceramics designer', 'DA', 'Job'),
    ('Engineer, water', 'TE', 'Job'),
    ('Sound technician, broadcasting/film/video', 'FT', 'Job'),
    ('Trade union research officer', 'FA', 'Job'),
    ('Drilling engineer', 'TE', 'Job'),
    ('Homeopath', 'HM', 'Job'),
    ('Health promotion specialist', 'HMH', 'Job'),
    ('Insurance broker', 'FA', 'Job'),
    ('Media buyer', 'DA', 'Job'),
    ('Water engineer', 'TE', 'Job'),
    ('Archaeologist', 'SR', 'Job'),
    ('Radiation protection practitioner', 'HMH', 'Job'),
    ('Physiological scientist', 'SR', 'Job'),
    ('Retail manager', 'FA', 'Job'),
    ('Production assistant, television', 'FT', 'Job'),
    ('Curator', 'DA', 'Job'),
    ('Secondary school teacher', 'ED', 'Job'),
    ('Engineer, land', 'TE', 'Job'),
    ('Designer, fashion/clothing', 'DA', 'Job'),
    ('Research scientist (maths)', 'SR', 'Job'),
    ('Social worker', 'HMH', 'Job'),
    ('Retail banker', 'FA', 'Job'),
    ('Interior and spatial designer', 'DA', 'Job'),
    ('Psychologist, clinical', 'HMH', 'Job'),
    ('Information systems manager', 'TE', 'Job'),
    ('Pension scheme manager', 'FA', 'Job'),
    ('Education officer, environmental', 'ED', 'Job'),
    ('Clinical embryologist', 'HMH', 'Job'),
    ('Lecturer, further education', 'ED', 'Job'),
    ('IT technical support officer', 'TE', 'Job'),
    ('Arts development officer', 'DA', 'Job'),
    ('Administrator, charities/voluntary organisations', 'FA', 'Job'),
    ('Engineer, automotive', 'TE', 'Job'),
    ('Surveyor, minerals', 'SR', 'Job'),
    ('English as a second language teacher', 'ED', 'Job'),
    ('Television/film/video producer', 'FT', 'Job'),
    ('Engineer, aeronautical', 'TE', 'Job'),
    ('Adult nurse', 'HMH', 'Job'),
    ('Pharmacologist', 'HM', 'Job'),
    ('Museum/gallery conservator', 'DA', 'Job'),
    ('Chartered legal executive (England and Wales)', 'LL', 'Job'),
    ('Psychiatrist', 'HMH', 'Job'),
    ('Immunologist', 'SR', 'Job'),
    ('Animal technologist', 'SR', 'Job'),
    ('Water quality scientist', 'SR', 'Job'),
    ('Designer, interior/spatial', 'DA', 'Job'),
    ('Surveyor, rural practice', 'SR', 'Job'),
    ('Training and development officer', 'ED', 'Job'),
    ('Loss adjuster, chartered', 'FA', 'Job'),
    ('Engineer, site', 'TE', 'Job'),
    ('Economist', 'FA', 'Job'),
    ('Tourist information centre manager', 'FT', 'Job'),
    ('Print production planner', 'DA', 'Job'),
    ('Administrator, local government', 'FA', 'Job'),
    ('Futures trader', 'FA', 'Job'),
    ('Copy', 'DA', 'Job'),
    ('Engineer, building services', 'TE', 'Job'),
    ('Therapist, occupational', 'HMH', 'Job'),
    ('Nutritional therapist', 'HMH', 'Job'),
    ('Volunteer coordinator', 'FA', 'Job'),
    ('Surveyor, planning and development', 'SR', 'Job'),
    ('Conservator, museum/gallery', 'DA', 'Job'),
    ('Public relations officer', 'DA', 'Job'),
    ('Advertising account planner', 'DA', 'Job'),
    ('Lecturer, higher education', 'ED', 'Job'),
    ('Scientist, forensic', 'SR', 'Job'),
    ('Lighting technician, broadcasting/film/video', 'FT', 'Job'),
    ('Medical technical officer', 'HMH', 'Job'),
    ('Sports development officer', 'FT', 'Job'),
    ('Maintenance engineer', 'TE', 'Job'),
    ('Chartered public finance accountant', 'FA', 'Job'),
    ('Medical laboratory scientific officer', 'HMH', 'Job'),
    ('Race relations officer', 'HMH', 'Job'),
    ('Insurance underwriter', 'FA', 'Job'),
    ('Multimedia programmer', 'DA', 'Job'),
    ('Designer, exhibition/display', 'DA', 'Job'),
    ('Dramatherapist', 'HMH', 'Job'),
    ('Merchant navy officer', 'TE', 'Job'),
    ('Surveyor, mining', 'SR', 'Job'),
    ('Press photographer', 'FT', 'Job'),
    ('Quarry manager', 'AG', 'Job'),
    ('Ecologist', 'SR', 'Job'),
    ('Engineer, agricultural', 'TE', 'Job'),
    ('Analytical chemist', 'SR', 'Job'),
    ('Translator', 'DA', 'Job'),
    ('Scientist, research (maths)', 'SR', 'Job'),
    ('Personnel officer', 'FA', 'Job'),
    ('Air broker', 'FA', 'Job'),
    ('Fast food restaurant manager', 'FA', 'Job'),
    ('Museum/gallery exhibitions officer', 'DA', 'Job'),
    ('Plant breeder/geneticist', 'AG', 'Job'),
    ('Logistics and distribution manager', 'FA', 'Job'),
    ('Cytogeneticist', 'SR', 'Job'),
    ('Theatre stage manager', 'DA', 'Job'),
	('Local government officer', 'FA', 'Job'),
    ('Psychologist, educational', 'ED', 'Job'),
    ('Careers information officer', 'ED', 'Job'),
    ('Operations geologist', 'TE', 'Job'),
    ('Astronomer', 'SR', 'Job'),
    ('Therapist, art', 'HMH', 'Job'),
    ('Special educational needs teacher', 'ED', 'Job'),
    ('Social research officer, government', 'SR', 'Job'),
    ('Dealer', 'FA', 'Job'),
    ('Forensic psychologist', 'HMH', 'Job'),
    ('Forest/woodland manager', 'AG', 'Job'),
    ('Brewing technologist', 'HMH', 'Job'),
    ('Freight forwarder', 'FA', 'Job'),
    ('English as a foreign language teacher', 'ED', 'Job'),
    ('Investment banker, corporate', 'FA', 'Job'),
    ('Accountant, chartered', 'FA', 'Job'),
    ('Land', 'AG', 'Job'),
    ('Equality and diversity officer', 'FA', 'Job'),
    ('Osteopath', 'HMH', 'Job'),
    ('Scientist, clinical (histocompatibility and immunogenetics)', 'SR', 'Job'),
    ('Teacher, early years/pre', 'ED', 'Job'),
    ('Police officer', 'LL', 'Job'),
    ('Engineer, energy', 'TE', 'Job'),
    ('Patent examiner', 'TE', 'Job'),
    ('Facilities manager', 'FA', 'Job'),
    ('Editor, commissioning', 'FT', 'Job'),
    ('Applications developer', 'TE', 'Job'),
    ('Claims inspector/assessor', 'FA', 'Job'),
    ('Landscape architect', 'DA', 'Job'),
    ('Research scientist (physical sciences)', 'SR', 'Job'),
    ('Music therapist', 'HMH', 'Job'),
    ('General practice doctor', 'HMH', 'Job'),
    ('Financial planner', 'FA', 'Job'),
    ('Leisure centre manager', 'FA', 'Job'),
    ('Sports therapist', 'HMH', 'Job'),
    ('Producer, radio', 'FT', 'Job'),
    ('Surgeon', 'HMH', 'Job'),
    ('Financial controller', 'FA', 'Job'),
    ('Social researcher', 'SR', 'Job'),
    ('Health and safety inspector', 'HMH', 'Job'),
    ('Commercial/residential surveyor', 'DA', 'Job'),
    ('Engineer, civil (contracting)', 'TE', 'Job'),
    ('Engineer, drilling', 'TE', 'Job'),
    ('Therapeutic radiographer', 'HMH', 'Job'),
    ('Nurse, adult', 'HMH', 'Job'),
    ('Designer, textile', 'DA', 'Job'),
    ('Energy engineer', 'TE', 'Job'),
    ('Charity officer', 'FA', 'Job'),
    ('Equities trader', 'FA', 'Job'),
    ('Recycling officer', 'SR', 'Job'),
    ('Film/video editor', 'FT', 'Job'),
    ('Civil Service administrator', 'FA', 'Job'),
    ('Designer, blown glass/stained glass', 'DA', 'Job'),
    ('Scientist, research (medical)', 'SR', 'Job'),
    ('Accounting technician', 'FA', 'Job'),
    ('International aid/development worker', 'FA', 'Job'),
    ('Actuary', 'FA', 'Job'),
    ('Commercial horticulturist', 'AG', 'Job'),
    ('Accommodation manager', 'FA', 'Job'),
    ('Geologist, engineering', 'TE', 'Job'),
    ('Immigration officer', 'FA', 'Job'),
    ('Psychologist, prison and probation services', 'HMH', 'Job'),
    ('Musician', 'DA', 'Job'),
    ('Conservation officer, nature', 'DA', 'Job'),
    ('Chartered certified accountant', 'FA', 'Job'),
    ('Midwife', 'HMH', 'Job'),
    ('Network engineer', 'TE', 'Job'),
    ('Presenter, broadcasting', 'FT', 'Job'),
    ('Event organiser', 'FA', 'Job'),
    ('Hotel manager', 'FA', 'Job'),
    ('Biochemist, clinical', 'HMH', 'Job'),
    ('Conservation officer, historic buildings', 'DA', 'Job'),
    ('Fashion designer', 'DA', 'Job'),
    ('Glass blower/designer', 'DA', 'Job'),
    ('Geophysical data processor', 'SR', 'Job'),
    ('Museum education officer', 'DA', 'Job'),
    ('Nurse, learning disability', 'HMH', 'Job'),
    ('Bookseller', 'DA', 'Job'),
    ('Further education lecturer', 'ED', 'Job'),
    ('Estate manager/land agent', 'FA', 'Job'),
    ('Radio producer', 'FT', 'Job'),
    ('Orthoptist', 'HMH', 'Job'),
    ('Health service manager', 'HMH', 'Job'),
    ('Engineer, mining', 'TE', 'Job'),
    ('Media planner', 'DA', 'Job'),
    ('Physiotherapist', 'HMH', 'Job'),
    ('Scientist, marine', 'SR', 'Job'),
    ('Broadcast engineer', 'FT', 'Job'),
    ('Armed forces technical officer', 'FA', 'Job'),
    ('Armed forces operational officer', 'FA', 'Job'),
    ('Educational psychologist', 'ED', 'Job'),
    ('Engineer, maintenance', 'TE', 'Job'),
    ('Paramedic', 'HMH', 'Job'),
    ('Horticultural therapist', 'HMH', 'Job'),
    ('Broadcast presenter', 'FT', 'Job'),
    ('Doctor, hospital', 'HMH', 'Job'),
    ('Accountant, chartered certified', 'FA', 'Job'),
    ('Politician''s assistant', 'FA', 'Job'),
    ('Psychotherapist', 'HMH', 'Job'),
    ('Publishing rights manager', 'DA', 'Job'),
	    ('Scientist, research (physical sciences)', 'SR', 'Job'),
    ('Manufacturing engineer', 'TE', 'Job'),
    ('Accountant, chartered management', 'FA', 'Job'),
    ('Industrial/product designer', 'DA', 'Job'),
    ('Recruitment consultant', 'FA', 'Job'),
    ('Agricultural consultant', 'AG', 'Job'),
    ('Insurance account manager', 'FA', 'Job'),
    ('Horticultural consultant', 'AG', 'Job'),
    ('Computer games developer', 'TE', 'Job'),
    ('Air cabin crew', 'FT', 'Job'),
    ('Surveyor, building control', 'DA', 'Job'),
    ('Tax inspector', 'FA', 'Job'),
    ('Environmental health practitioner', 'HMH', 'Job'),
    ('Restaurant manager, fast food', 'FA', 'Job'),
    ('Architectural technologist', 'DA', 'Job'),
    ('Theatre manager', 'DA', 'Job'),
    ('Physicist, medical', 'HMH', 'Job'),
    ('Forensic scientist', 'SR', 'Job'),
    ('Advice worker', 'HMH', 'Job'),
    ('Administrator', 'FA', 'Job'),
    ('Editor, magazine features', 'FT', 'Job'),
    ('Armed forces logistics/support/administrative officer', 'FA', 'Job'),
    ('Runner, broadcasting/film/video', 'FT', 'Job'),
    ('Holiday representative', 'FT', 'Job'),
    ('Tree surgeon', 'AG', 'Job'),
    ('Minerals surveyor', 'SR', 'Job'),
    ('Public house manager', 'FA', 'Job'),
    ('Chiropractor', 'HMH', 'Job'),
    ('Management consultant', 'FA', 'Job'),
    ('Psychologist, counselling', 'HMH', 'Job'),
    ('Geologist, wellsite', 'SR', 'Job'),
    ('Sales professional, IT', 'TE', 'Job'),
    ('TEFL teacher', 'ED', 'Job'),
    ('Surveyor, quantity', 'DA', 'Job'),
    ('Industrial buyer', 'FA', 'Job'),
    ('Pharmacist, community', 'HMH', 'Job'),
    ('Youth worker', 'HMH', 'Job'),
    ('Pathologist', 'HMH', 'Job'),
    ('Probation officer', 'HMH', 'Job'),
    ('Manufacturing systems engineer', 'TE', 'Job'),
    ('Video editor', 'FT', 'Job'),
    ('Psychotherapist, dance movement', 'HMH', 'Job'),
    ('Herbalist', 'HMH', 'Job'),
    ('Graphic designer', 'DA', 'Job'),
    ('Designer, ceramics/pottery', 'DA', 'Job'),
    ('Science writer', 'DA', 'Job'),
    ('Administrator, education', 'ED', 'Job'),
    ('Contracting civil engineer', 'TE', 'Job'),
    ('Dentist', 'HMH', 'Job'),
    ('Electrical engineer', 'TE', 'Job'),
    ('Aid worker', 'FA', 'Job'),
    ('Development worker, international aid', 'FA', 'Job'),
    ('Research officer, political party', 'FA', 'Job'),
    ('IT sales professional', 'FA', 'Job'),
    ('Veterinary surgeon', 'HMH', 'Job'),
    ('Clinical psychologist', 'HMH', 'Job'),
    ('Telecommunications researcher', 'TE', 'Job'),
    ('Clinical research associate', 'HMH', 'Job'),
    ('Exhibition designer', 'DA', 'Job'),
    ('Textile designer', 'DA', 'Job'),
    ('Teacher, music', 'ED', 'Job'),
    ('Engineer, broadcasting (operations)', 'TE', 'Job'),
    ('Designer, industrial/product', 'DA', 'Job'),
    ('Product/process development scientist', 'SR', 'Job'),
    ('Editorial assistant', 'DA', 'Job'),
    ('Museum/gallery curator', 'DA', 'Job'),
    ('Administrator, Civil Service', 'FA', 'Job'),
    ('Clinical biochemist', 'HMH', 'Job'),
    ('Early years teacher', 'ED', 'Job'),
    ('Stage manager', 'DA', 'Job'),
    ('Tax adviser', 'FA', 'Job'),
    ('Occupational therapist', 'HMH', 'Job'),
    ('Secretary, company', 'FA', 'Job'),
    ('Warehouse manager', 'FA', 'Job'),
    ('Animal nutritionist', 'AG', 'Job'),
    ('Newspaper journalist', 'FT', 'Job'),
    ('Market researcher', 'FA', 'Job'),
    ('Building surveyor', 'DA', 'Job'),
    ('Community pharmacist', 'HMH', 'Job'),
    ('Journalist, magazine', 'FT', 'Job'),
    ('Press sub', 'FT', 'Job'),
    ('Higher education careers adviser', 'ED', 'Job'),
    ('Database administrator', 'TE', 'Job'),
    ('Dancer', 'DA', 'Job'),
    ('Private music teacher', 'DA', 'Job'),
    ('Engineer, structural', 'TE', 'Job'),
    ('Radiographer, diagnostic', 'HMH', 'Job'),
    ('Technical sales engineer', 'TE', 'Job'),
    ('Child psychotherapist', 'HMH', 'Job'),
    ('Theme park manager', 'FA', 'Job'),
    ('Structural engineer', 'TE', 'Job'),
    ('Writer', 'DA', 'Job'),
    ('Clinical cytogeneticist', 'HMH', 'Job'),
    ('Nurse, mental health', 'HMH', 'Job'),
    ('Trading standards officer', 'FA', 'Job'),
    ('Meteorologist', 'SR', 'Job'),
    ('Programmer, multimedia', 'TE', 'Job'),
    ('Planning and development surveyor', 'DA', 'Job'),
    ('Emergency planning/management officer', 'FA', 'Job'),
    ('Sports administrator', 'FA', 'Job'),
	    ('Restaurant manager', 'FA', 'Job'),
    ('Hospital pharmacist', 'HMH', 'Job'),
    ('Chartered management accountant', 'FA', 'Job'),
    ('Education officer, museum', 'ED', 'Job'),
    ('Civil engineer, consulting', 'TE', 'Job'),
    ("Barrister's clerk", 'LL', 'Job'),
    ('Conference centre manager', 'DA', 'Job'),
    ('Heritage manager', 'DA', 'Job'),
    ('Scientist, research (life sciences)', 'SR', 'Job'),
    ('Aeronautical engineer', 'TE', 'Job'),
    ('Dispensing optician', 'HMH', 'Job'),
    ('Legal secretary', 'LL', 'Job'),
    ('Public relations account executive', 'DA', 'Job'),
    ('Marine scientist', 'SR', 'Job'),
    ('Horticulturist, commercial', 'AG', 'Job'),
    ('Records manager', 'DA', 'Job'),
    ('Oncologist', 'HMH', 'Job'),
    ('Financial trader', 'FA', 'Job'),
    ('Retail merchandiser', 'DA', 'Job'),
    ('Engineer, manufacturing systems', 'TE', 'Job'),
    ('Firefighter', 'HMH', 'Job'),
    ('Embryologist, clinical', 'HMH', 'Job'),
    ('Government social research officer', 'SR', 'Job'),
    ('Publishing copy', 'DA', 'Job'),
    ('Public librarian', 'DA', 'Job'),
    ('Passenger transport manager', 'FA', 'Job'),
    ('Ship broker', 'FA', 'Job'),
    ('Scientist, product/process development', 'SR', 'Job'),
    ('IT trainer', 'TE', 'Job'),
    ('Games developer', 'FT', 'Job'),
    ('Programmer, applications', 'TE', 'Job'),
    ('Teacher, primary school', 'ED', 'Job'),
    ('Engineer, electrical', 'TE', 'Job'),
    ('Quantity surveyor', 'DA', 'Job'),
    ('Producer, television/film/video', 'FT', 'Job'),
    ('Therapist, music', 'HMH', 'Job'),
    ('Pharmacist, hospital', 'HMH', 'Job'),
    ('Health visitor', 'HMH', 'Job'),
    ('Rural practice surveyor', 'DA', 'Job'),
    ('Chartered loss adjuster', 'FA', 'Job'),
    ('Teacher, adult education', 'ED', 'Job'),
    ('Haematologist', 'HMH', 'Job'),
    ('Community education officer', 'ED', 'Job'),
    ('Music tutor', 'DA', 'Job'),
    ('Production designer, theatre/television/film', 'FT', 'Job'),
    ('Editor, film/video', 'FT', 'Job'),
    ('Counselling psychologist', 'HMH', 'Job'),
    ('Arts administrator', 'DA', 'Job'),
    ('Scientific laboratory technician', 'SR', 'Job'),
    ('Lobbyist', 'FA', 'Job'),
    ('Surveyor, land/geomatics', 'DA', 'Job'),
    ('Programmer, systems', 'TE', 'Job'),
    ('Mechanical engineer', 'TE', 'Job'),
    ('Architect', 'DA', 'Job'),
    ('Geochemist', 'SR', 'Job'),
    ('Engineer, biomedical', 'TE', 'Job'),
    ('Medical illustrator', 'DA', 'Job'),
    ('Make', 'DA', 'Job'),
    ('Diagnostic radiographer', 'HMH', 'Job'),
    ('Psychologist, forensic', 'HMH', 'Job'),
    ('Public affairs consultant', 'FA', 'Job'),
    ('Air traffic controller', 'FA', 'Job'),
    ('Microbiologist', 'SR', 'Job'),
    ('Illustrator', 'DA', 'Job'),
    ('Bonds trader', 'FA', 'Job'),
    ('Garment/textile technologist', 'DA', 'Job'),
    ('Occupational psychologist', 'HMH', 'Job'),
    ('Dance movement psychotherapist', 'HMH', 'Job'),
    ('Animator', 'FT', 'Job'),
    ('Actor', 'FT', 'Job'),
    ('Buyer, retail', 'FA', 'Job'),
    ('Librarian, academic', 'DA', 'Job'),
    ('Transport planner', 'FA', 'Job'),
    ('Chiropodist', 'HMH', 'Job'),
    ('Tourism officer', 'FA', 'Job'),
    ('Research officer, trade union', 'FA', 'Job'),
    ('Jewellery designer', 'DA', 'Job'),
    ('Sub', 'FT', 'Job'),
    ('Therapist, drama', 'HMH', 'Job'),
    ('Licensed conveyancer', 'LL', 'Job'),
    ('Ophthalmologist', 'HMH', 'Job'),
    ('Investment banker, operational', 'FA', 'Job'),
    ('Geoscientist', 'SR', 'Job'),
    ('Designer, graphic', 'DA', 'Job'),
    ('Secretary/administrator', 'FA', 'Job'),
    ('Designer, furniture', 'DA', 'Job'),
    ('Chemist, analytical', 'SR', 'Job'),
    ('Systems analyst', 'TE', 'Job'),
    ('Environmental education officer', 'ED', 'Job'),
    ('Sports coach', 'FA', 'Job'),
    ('Petroleum engineer', 'TE', 'Job'),
    ('Pilot, airline', 'FA', 'Job'),
    ('Surveyor, hydrographic', 'DA', 'Job'),
    ('Best boy', 'FT', 'Job'),
    ('Clothing/textile technologist', 'DA', 'Job'),
    ('Speech and language therapist', 'HMH', 'Job'),
    ('Web designer', 'DA', 'Job'),
    ('Research officer, government', 'FA', 'Job'),
    ('Consulting civil engineer', 'TE', 'Job'),
    ('Software engineer', 'TE', 'Job'),
	    ('Civil engineer, contracting', 'TE', 'Job'),
    ('Engineer, civil (consulting)', 'TE', 'Job'),
    ('Radiographer, therapeutic', 'HMH', 'Job'),
    ('Artist', 'DA', 'Job'),
    ('Production engineer', 'TE', 'Job'),
    ('Teacher, secondary school', 'ED', 'Job'),
    ('Fine artist', 'DA', 'Job'),
    ('Housing manager/officer', 'FA', 'Job'),
    ('Materials engineer', 'TE', 'Job'),
    ('Product designer', 'DA', 'Job'),
    ('Paediatric nurse', 'HMH', 'Job'),
    ('Building services engineer', 'TE', 'Job'),
    ('Psychologist, occupational', 'HMH', 'Job'),
    ('Therapist, speech and language', 'HMH', 'Job'),
    ('Hydrographic surveyor', 'DA', 'Job'),
    ('Statistician', 'SR', 'Job'),
    ('Scientist, physiological', 'SR', 'Job'),
    ('Geneticist, molecular', 'SR', 'Job'),
    ('Environmental manager', 'FA', 'Job'),
    ('Personal assistant', 'FA', 'Job'),
    ('Intelligence analyst', 'FA', 'Job'),
    ('Journalist, broadcasting', 'FT', 'Job'),
    ('Automotive engineer', 'TE', 'Job'),
    ('Commercial art gallery manager', 'DA', 'Job'),
    ('Engineering geologist', 'TE', 'Job'),
    ('Clinical molecular geneticist', 'HMH', 'Job'),
    ('Chartered accountant', 'FA', 'Job'),
    ('Teaching laboratory technician', 'ED', 'Job'),
    ('Surveyor, insurance', 'DA', 'Job'),
    ('Community arts worker', 'DA', 'Job'),
    ('Psychologist, sport and exercise', 'HMH', 'Job'),
    ('Academic librarian', 'DA', 'Job'),
    ('Operational researcher', 'SR', 'Job'),
    ('Learning mentor', 'ED', 'Job'),
    ('Horticulturist, amenity', 'AG', 'Job'),
    ('Systems developer', 'TE', 'Job'),
    ('Visual merchandiser', 'DA', 'Job'),
    ('Arboriculturist', 'AG', 'Job'),
    ('Metallurgist', 'SR', 'Job'),
    ('Education officer, community', 'ED', 'Job'),
    ('Surveyor, building', 'DA', 'Job'),
    ('Quality manager', 'FA', 'Job'),
    ('Mental health nurse', 'HMH', 'Job'),
    ('Psychotherapist, child', 'HMH', 'Job'),
    ('Magazine journalist', 'FT', 'Job'),
    ('Prison officer', 'HMH', 'Job'),
    ('Human resources officer', 'FA', 'Job'),
    ('Community development worker', 'FA', 'Job'),
    ('Art gallery manager', 'DA', 'Job'),
    ('Engineer, production', 'TE', 'Job'),
    ('Historic buildings inspector/conservation officer', 'DA', 'Job'),
    ('Counsellor', 'HMH', 'Job'),
    ('Therapist, nutritional', 'HMH', 'Job'),
    ('Magazine features editor', 'FT', 'Job'),
    ('Furniture conservator/restorer', 'DA', 'Job'),
    ('Ranger/warden', 'DA', 'Job'),
    ('Theatre director', 'DA', 'Job'),
    ('Tour manager', 'FA', 'Job'),
    ('Engineer, control and instrumentation', 'TE', 'Job'),
    ('Amenity horticulturist', 'AG', 'Job'),
    ('Information officer', 'DA', 'Job'),
    ('Exhibitions officer, museum/gallery', 'DA', 'Job'),
    ('Buyer, industrial', 'FA', 'Job'),
    ('Energy manager', 'FA', 'Job'),
    ('Programme researcher, broadcasting/film/video', 'FT', 'Job'),
    ('Armed forces training and education officer', 'FA', 'Job'),
    ('Technical author', 'DA', 'Job'),
    ('Data processing manager', 'TE', 'Job'),
    ('Geographical information systems officer', 'DA', 'Job'),
    ('Toxicologist', 'HMH', 'Job'),
    ('Administrator, sports', 'FA', 'Job'),
    ('Clinical scientist, histocompatibility and immunogenetics', 'HMH', 'Job'),
    ('Civil Service fast streamer', 'FA', 'Job'),
    ('Naval architect', 'TE', 'Job'),
    ('Retail buyer', 'FA', 'Job'),
    ('Exercise physiologist', 'HMH', 'Job'),
    ('Marketing executive', 'FA', 'Job'),
    ('Corporate investment banker', 'FA', 'Job'),
    ('Advertising copywriter', 'DA', 'Job'),
    ('Gaffer', 'FT', 'Job'),
    ('Electronics engineer', 'TE', 'Job'),
    ('Surveyor, commercial/residential', 'DA', 'Job'),
    ('Nurse, children', 'HMH', 'Job'),
    ('Regulatory affairs officer', 'FA', 'Job'),
    ('Photographer', 'DA', 'Job'),
    ('Land/geomatics surveyor', 'DA', 'Job'),
    ('Research scientist (life sciences)', 'SR', 'Job'),
    ('Patent attorney', 'LL', 'Job'),
    ('Radio broadcast assistant', 'FT', 'Job'),
    ('Technical brewer', 'DA', 'Job'),
    ('Higher education lecturer', 'ED', 'Job'),
    ('Careers adviser', 'ED', 'Job'),
    ('Scientist, audiological', 'HMH', 'Job'),
    ('Optician, dispensing', 'HMH', 'Job'),
    ('Education administrator', 'ED', 'Job'),
    ('Camera operator', 'FT', 'Job'),
    ('Archivist', 'DA', 'Job'),
    ('Ambulance person', 'HMH', 'Job'),
    ('Town planner', 'FA', 'Job'),
    ('Waste management officer', 'FA', 'Job'),
	('Barrister', 'LL', 'Job'),
    ('Financial risk analyst', 'FA', 'Job'),
    ('Colour technologist', 'DA', 'Job'),
    ('Nature conservation officer', 'DA', 'Job'),
    ('Doctor, general practice', 'HMH', 'Job'),
    ('Sales promotion account executive', 'FA', 'Job'),
    ('Airline pilot', 'FT', 'Job'),
    ('Engineer, chemical', 'TE', 'Job'),
    ('Engineer, technical sales', 'TE', 'Job'),
    ('Therapist, sports', 'HMH', 'Job'),
    ('Pensions consultant', 'FA', 'Job'),
    ('Diplomatic Services operational officer', 'FA', 'Job'),
    ('Biomedical scientist', 'SR', 'Job'),
    ('Catering manager', 'DA', 'Job'),
    ('Geophysicist/field seismologist', 'TE', 'Job'),
    ('Travel agency manager', 'DA', 'Job'),
    ('Senior tax professional/tax inspector', 'FA', 'Job'),
    ('Banker', 'FA', 'Job'),
    ('Audiological scientist', 'HMH', 'Job'),
    ('Estate agent', 'DA', 'Job'),
    ('Trade mark attorney', 'LL', 'Job'),
    ('Special effects artist', 'FT', 'Job'),
    ('Investment analyst', 'FA', 'Job'),
    ("Nurse, children's", 'HM', 'Job'),
    ("Politician's assistant", 'FA', 'Job'),
    ('Solicitor, Scotland', 'LL', 'Job')
]

job_category = [
    ('HM', 'Healthcare and Medicine', 'Category'),
    ('ED', 'Education', 'Category'),
    ('FT', 'Film and Television', 'Category'),
    ('HMH', 'Health and Mental Health', 'Category'),
    ('LL', 'Law and Legal', 'Category'),
    ('TE', 'Technology and Engineering', 'Category'),
    ('DA', 'Design and Arts', 'Category'),
    ('FA', 'Finance and Accounting', 'Category'),
    ('SR', 'Science and Research', 'Category')
]

df = states + platform + card + job_list + job_category

data = pd.DataFrame(df, columns=['CodeID', 'CodeValue', 'CodeName'])
